.PHONY: build
build:
	cargo build -C ..

.PHONY: build-release
build-release:
	cargo build -C .. --release

.PHONY: fmt
fmt:
	cargo fmt -C ..

.PHONY: fmt-check
fmt-check:
	cargo fmt -C .. --check

.PHONY: clippy
clippy:
	cargo clippy -C ..

.PHONY: test
test:
	cargo test -C ..

.PHONY: clean
clean:
	cargo clean -C ..
